export const monsterArray = {
  0: {
    name: "octopus shooting at you",
    src: "assets/critters/hardboiled_octopus.png",
    width: 50,
    height: 50,
    radius: 25,
    health: 10,
    moveSpeed: 0,
    points: 100,
    yPos: 375,
  },
  1: {
    name: "bats diving at you",
    src: "assets/critters/hardboiled_octopus.png",
    width: 50,
    height: 50,
    radius: 25,
    health: 10,
    moveSpeed: 5,
    points: 100,
    yPos: 50,
  },
  2: {
    name: "slimes falling down",
    src: "assets/critters/hardboiled_octopus.png",
    width: 50,
    height: 50,
    radius: 25,
    health: 10,
    moveSpeed: 0,
    points: 100,
    yPos: 50,
  }
}